<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>proposal-gravitational-circular-transport-system</title>
<link rel="stylesheet" href="https://stackedit.io/res-min/themes/base.css" />
<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
</head>
<body><div class="container"><p>TL;DR: An idea about contract and expand space-time non-symmetrically via Doppler effect of gravitational wave, so we can cheat to “fold” space-time and travel faster, even fast enough to <strong>apparently</strong> faster than light to a distant observer.</p>



<h1 id="theoretical-proposal-of-gravitational-circular-rapid-transport-system">Theoretical Proposal of Gravitational Circular Rapid Transport System</h1>



<h2 id="inspiration">Inspiration</h2>

<p>In the recent discuss with Professor Chu Ming Chung, we concluded that theoretically, if we can produce sufficient gravitational wave from a massive object that is moving in an extreme speed, it is possible to achieve faster-than-light travel relative to a inertial reference frame. </p>

<p><img src="https://upload.wikimedia.org/wikipedia/commons/b/b8/Wavy.gif" alt="Gravitational wave from a pair of neutron stars orbiting." title="Gravitational wave from a pair of neutron stars orbiting."> <br>
Two-dimensional representation of gravitational waves generated by two neutron stars orbiting each other. From Wikipedia., licensed under Public Domain.</p>

<p><img src="https://upload.wikimedia.org/wikipedia/commons/d/d4/Velocity0_70c.jpg" alt="Relativistic Doppler effect of light wave" title="Relativistic Doppler effect of light wave"> <br>
A source of light waves moving to the right, relative to observers, with velocity 0.7c. The frequency is higher for observers on the right, and lower for observers on the left. From Wikipedia, attribution “By en:TxAlien - en:Image:Velocity0 70c.jpg, CC BY-SA 3.0, <a href="https://commons.wikimedia.org/w/index.php?curid=1066460">https://commons.wikimedia.org/w/index.php?curid=1066460</a>“.</p>

<p>The concept is quite simple, because of the relativistic Doppler effect, given a very fast gravitational wave source, those gravitational wave produced will contract along the moving direction of such object, and expand opposite the moving direction of such object. It is believed that these gravitational wave will distort space-time to contract and expand respectively. It is thought that these non-symmetrical distortion to space-time will allow faster-than-light travel relative to a far apart reference frame, but remains slower than light in the current reference frame. Such an idea is in fact inspired from the idea of warp engine (<a href="https://en.wikipedia.org/wiki/Alcubierre_drive" title="Alcubierre warp drive">Alcubierre warp drive</a>), but distortion to space-time is caused by <strong>Doppler effect of gravitational wave</strong> instead of the space-time expansion due to negative mass.</p>



<h2 id="difficulties">Difficulties</h2>

<p>However, such approach is extremely difficult to turn into practice. </p>

<p><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Gravitation_space_source.svg/869px-Gravitation_space_source.svg.png" alt="Mass-energy warps spacetime." title="Mass-energy warps spacetime."> <br>
Mass-energy warps space-time. From Wikipedia.</p>

<p>It is known that even a neutron star can only distort space-time at a ratio of <script type="math/tex" id="MathJax-Element-1">10\%</script>, which means such object have to be extremely massive, i.e. black hole. </p>

<iframe src="//commons.wikimedia.org/wiki/File:Warped_Space_and_Time_Around_Colliding_Black_Holes_(Courtesy_Caltech-MIT-LIGO_Laboratory,_produced_by_SXS_project).webm?embedplayer=yes" width="854" height="480" allowfullscreen=""></iframe>

<p>Warped space-time around colliding black holes. From Wikipedia.</p>

<p>Scientist also observed that even in a extremely large-scale gravitational event like merge of black-holes, only a small proportion amount of energy, approximately <script type="math/tex" id="MathJax-Element-2">3\%</script> is converted into gravitational energy, and hence far from enough to cover the length contraction and time dilation effect due to the distortion to time-space of normal gravity, which actually slow down the object for a far apart observer. i believe a much bigger ratio is required for that.</p>

<p>Moreover, given a massive enough star, it will take a very large amount of energy to move it in a speed that Doppler effect can be significant.</p>

<p>Therefore, it is nearly impossible to achieve that kind of mass, acceleration and speed in the same time if we are talking about a linear motion, but what about <strong>circular motion</strong>?</p>



<h2 id="the-binary-star-system">The binary star system</h2>

<p>It is discussed in Wikipedia that a binary star system can generate gravitational wave. As stated above, to generate such non-symmetrical distortion to time-space, a combination of extreme mass, acceleration and speed is required. Due to my insufficient mathematics skill to analysis such acceleration due to gravitation field, I would like to provide an approximate algebra approach with Newton’s law of gravitation and proper acceleration for relativistic circular motion here. Such equation is given by <script type="math/tex" id="MathJax-Element-3">a={GM}/{\left(2r\right)^2}= \gamma^2 {v^2}/{2r} </script>, resulting in: </p>



<p><script type="math/tex; mode=display" id="MathJax-Element-4">GM\propto \left(\gamma v\right)^2 r =  \left(\gamma \omega \right)^2 r^3</script></p>

<p>Note that such <script type="math/tex" id="MathJax-Element-5">r</script> refers to the radius of orbit. It describes a very complex mathematical relationship, causing such system very hard to construct. To achieve a large <script type="math/tex" id="MathJax-Element-6">v</script> to approach speed of light, it requires a large <script type="math/tex" id="MathJax-Element-7">r</script> since a large <script type="math/tex" id="MathJax-Element-8">\omega</script> can cause our massive object to leave its orbit. However, if <script type="math/tex" id="MathJax-Element-9">r</script> is actually too big, <script type="math/tex" id="MathJax-Element-10">M\propto \left(\gamma v\right)^2 r </script> implies that <script type="math/tex" id="MathJax-Element-11">v</script> have to be small, especially when the gravitational constant <script type="math/tex" id="MathJax-Element-12">G</script> is too small. And what even worse, look at that acceleration <script type="math/tex" id="MathJax-Element-13">a</script>, it is inversely proportional to <script type="math/tex" id="MathJax-Element-14">r^2</script>, which means if we get the radius big, we will have no acceleration to get enough gravitational wave.</p>

<p>Fortunately, there are a mathematics solution to that. Just increase <script type="math/tex" id="MathJax-Element-15">M</script> is enough, right? But we faces two practical problems here. Where in universe can you <strong>get an object with that mass</strong>? I suppose you can get something like a neutron star or black hole to do that, how on Earth can you <strong>find enough energy to push it into that kind of velocity</strong>?</p>

<p>However, how if what we get isn’t a pair of binary stars, but <strong>a bunch of stars orbiting in an orbit with a very massive stuff in the center of it</strong>?. </p>



<h2 id="the-flying-horses-system">The “flying horses” system</h2>



<h3 id="inspiration-1">Inspiration</h3>

<p><strong>Non-scientific off-topic alert !!!</strong></p>

<p>Some off-topic things here. Did you ever played those flying horses in the amusement park, imagining yourself to be Snow White or Prince Charming? To be honest I did that when I was a little primary kid. </p>

<p>When I am thinking about the way to increase such mass of that binary stars system, I was actually having my delicious and massive dinner in a class activity, watching my classmates playing games. </p>

<p>The shape of game they are playing sounds like that “flying horses”. They were playing a game that require the guy <strong>at the center</strong> close their eye and identify who did shouted, with everyone of others standing along a <strong>circle</strong>. </p>

<p>Watching them playing and running around leads to an circular orbit system as discussed below.</p>



<h3 id="multi-body-system">Multi-body system</h3>

<p><strong>How if we put some stars along a circular orbit?</strong> We know that gravity is <strong>super-positioning</strong>. They just <strong>sum up</strong> themselves. So if we managed to put 8 stars into the orbit, then each star will experience the gravitational field of all 7 stars, and it can be large! It can be even larger if we put 16, 32 or even more stars in it! That could be a very efficient way to compensate for the smaller <script type="math/tex" id="MathJax-Element-16">M</script> in each stars. That is many a little makes a mickle!</p>

<p><img src="https://i.imgur.com/tDgiN8O.gif" alt="Only stars in circular orbit" title="Only_stars_in_circular_orbit"></p>

<p>It could be even better if we put quite a large amount of <strong>planets</strong> or even just asteroids there, it just sums up. </p>

<p>Hence the large acceleration is provided with multiple source of gravity, allowing a larger <script type="math/tex" id="MathJax-Element-17">v</script> with larger <script type="math/tex" id="MathJax-Element-18">r</script>. However, since these surrounding objects may not be massive enough to produce enough gravitational wave, and it will be quite hard to push them into a large speed. Therefore, such surrounding objects should be <strong>as dense as possible</strong> to curve space-time enough to produce enough gravitational wave, can a neutron star make it? I believe it is possible to strike a balance to achieve enough space-time distortion while maintaining a large speed to entertain Doppler effect, so that the non-symmetrical distortion of space-time can be achieved and used.</p>

<p>But how if these objects are still not able to create strong enough gravitational field for the acceleration (actually not very likely)?</p>



<h3 id="a-super-massive-object-in-the-center">A super-massive object in the center ?</h3>

<p>I knows that even merging black hole can only convert <script type="math/tex" id="MathJax-Element-89">3\%</script> of total gravitational energy to gravitational wave, but we need even more. Our solution to that is even stronger gravitational field of lager acceleration with a <strong>super-massive object</strong> in the center of such system, some sort of black holes or extremely massive neutron stars. </p>

<p>Hey, how do we move such massive thing in favor of us? It is not quite possible, so instead of moving it, we build our system around it. Would it be favorable then? We just get enough gravity to do that?</p>

<p><img src="https://i.imgur.com/YLalqHIg.png" alt="Super massive object in the center" title="Super massive object in the center"></p>

<p>But, damn it! We forgot about the gravitational time dilation effect of the very big gravity from that massive star. To prevent that thing happen too seriously, we also need to strike a balance between gravitational acceleration it provides to us with its gravitational field and the time dilation effect it provides to us.</p>

<p>Perhaps it would be better if we never have to use that center object as a source of gravity, since it can have other usage.</p>

<h3 id="practical-usage">Practical usage</h3>

<p>In order to travel at large speed, passengers will have to get on and off from such stars. Instead of putting a extremely massive thing in the center of system, we can put a habitable planet or even some artificial structure there, and it allows passengers to reach those planets for travelling with some spaceships.</p>

<h3 id="even-more-ideas">Even more ideas</h3>

<h4 id="multiple-orbits">Multiple orbits</h4>

<p>Is it possible to put more than one orbits there? The objects in inner orbits can act as an efficient source of gravity for the outer objects as well.</p>

<h4 id="dyson-sphere">Dyson sphere</h4>

<p>As discussed above, It could be possible to put artificial habitable structure in the center of such system. How if we put a Dyson sphere there? If we habit inside such a Dyson sphere, the gravity from the orbiting objects can pull us so we still get some gravity!</p>

<h4 id="eclipse-orbit">Eclipse orbit</h4>

<p>One may say the range of this system is so short and it cannot perform long way inter-solar travel. How if we stretch the circle and get an eclipse orbit? Our choice of such center for Dyson sphere or other things should be the corresponding focus of eclipse.</p></div></body>
</html>